language: node_js
node_js:
<<<<<<< HEAD
  - "6.1"

services:
  - mongodb

# See: https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Meteor-Apps
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
=======
  - "6"

addons:
  code_climate:
    repo_token: 01887a8c261ce74478a89e2f2b022d83ba0d7e9b8fa2ff1a5e6f668c5532451c

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
>>>>>>> thing
